### PR TITLE
Babel6 conversion

### PR DESCRIPTION
**Pull request by ian-ross**
Don't know if you're interested in this, but we're using Babel 6, and the plugin setup has changed quite a bit from Babel 5.  This is a first attempt at updating your gettext extractor for those changes.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/babel-gettext-extractor/2)

### CODE REVIEW

**Comment by muffinresearch** [comment]
We're starting to use these patches over here on another temporary fork [1] and they look to be working fine. I'm curious to know if there's any plans to update this project to babel 6 in the near future?

[1] https://github.com/muffinresearch/babel-gettext-extractor

**Comment by mitsuhiko** [comment]
I will take a look at it.

**Comment by benvinegar** [comment]
@mitsuhiko – can you take another look? I've started upgrading getsentry/sentry to Babel 6, and this is the current blocker (support was added in the original [babel-gettext-plugin](https://github.com/jruchaud/babel-gettext-plugin/commit/a60014d52df8856e019e18f8f8c1360f5b0e862a)).

**Comment by benvinegar** [comment]
Closed in favor of #3 – publishing the Babel API changes in version 2.0.0

**Pull request closed without merging**
